-- MySQL Script generated by MySQL Workbench
-- Thu 05 Dec 2019 07:42:19 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pinf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pinf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pinf` DEFAULT CHARACTER SET latin1 ;
USE `pinf` ;

-- -----------------------------------------------------
-- Table `pinf`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinf`.`usuario` (
  `idusuario` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pinf`.`etiqueta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinf`.`etiqueta` (
  `idetiqueta` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL COMMENT 'Para que no se solapen las etiquetas de distintos usuarios que tengan un mismo nombre \nle añadiremos al principio el nombre del usuario (usuario_etiqueta) y dentro del modelo validaremos\nque no se utilice _ para nombres de usuarios y etiquetas.\n',
  `tipo` ENUM('evento', 'lugar', 'persona', 'tema') NULL DEFAULT NULL,
  `idusuario` INT(11) NOT NULL,
  PRIMARY KEY (`idetiqueta`),
  INDEX `fk_etiqueta_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_etiqueta_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `pinf`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pinf`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinf`.`imagen` (
  `idimagen` INT(11) NOT NULL,
  `fecha` VARCHAR(45) NULL DEFAULT NULL,
  `localizacion` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NOT NULL COMMENT 'nombre del fichero de imagen.',
  `idusuario` INT(11) NOT NULL,
  `camara` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idimagen`),
  INDEX `fk_imagen_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_imagen_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `pinf`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `pinf`.`etiqueta-imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pinf`.`etiqueta-imagen` (
  `idetiqueta` INT(11) NOT NULL,
  `idimagen` INT(11) NOT NULL,
  PRIMARY KEY (`idetiqueta`, `idimagen`),
  INDEX `fk_etiqueta-imagen_imagen_idx` (`idimagen` ASC),
  CONSTRAINT `fk_etiqueta-imagen_imagen`
    FOREIGN KEY (`idimagen`)
    REFERENCES `pinf`.`imagen` (`idimagen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_etiqueta-imagen_etiqueta1`
    FOREIGN KEY (`idetiqueta`)
    REFERENCES `pinf`.`etiqueta` (`idetiqueta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
